version: '3.8'

services:
  # 1. Service Web Server Apache + PHP 8.2
  web:
    container_name: jasukemazd_container
    image: php:8.2-apache
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    entrypoint: [ "sh", "-c", "docker-php-ext-install mysqli && docker-php-ext-enable mysqli && apache2-foreground" ]
    restart: always

  # 2. Service Database SQL (MySQL 8.0)
  db:
    container_name: jasukemazd_db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      # PENTING: Sesuaikan password dan nama DB ini dengan yang tertulis di pesanan.php kalian
      MYSQL_ROOT_PASSWORD: jasuke123
      MYSQL_DATABASE: jasuke_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data: